# Generated by Django 6.0.4 on 2026-04-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='For news/events, this is the main heading.', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Small text above or below title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Details of the event or news story.')),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('button_text', models.CharField(default='Learn More', max_length=50)),
                ('button_url', models.CharField(default='#', max_length=500)),
                ('is_news_event', models.BooleanField(default=False, help_text='Check this if the slide is a specific news story. Uncheck for general ministry branding.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which slides appear (0, 1, 2...)')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
