# Generated by Django 6.0.4 on 2026-04-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heroslide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroslide',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed text for news or events.', null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='is_news_event',
            field=models.BooleanField(default=False, help_text='Check this to show the specific title/desc typed above. Uncheck to show general branding text.'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of appearance (0, 1, 2...)'),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Small text above the main title.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='heroslide',
            name='title',
            field=models.CharField(blank=True, help_text='Heading for news/events. Leave blank for pure branding images.', max_length=200, null=True),
        ),
    ]
