# Generated by Django 6.0.4 on 2026-04-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_heroslide_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['featured_order', 'title'], 'verbose_name_plural': 'Ministries'},
        ),
        migrations.RemoveField(
            model_name='ministry',
            name='featured',
        ),
        migrations.AddField(
            model_name='ministry',
            name='featured_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ministry',
            name='show_on_slider',
            field=models.BooleanField(default=False, help_text='Check this to show in the homepage scroller'),
        ),
        migrations.AddField(
            model_name='ministry',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
