# Generated by Django 6.0.4 on 2026-04-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ministry_options_remove_ministry_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('day_and_time', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Brief description shown on hover.')),
                ('color', models.CharField(choices=[('red', 'Dim Red'), ('navy', 'Navy Blue')], default='red', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
