# Generated by Django 6.0.4 on 2026-04-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_leader'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('about', 'About Us Page'), ('leadership', 'Leadership Page'), ('events', 'Events Page'), ('contact', 'Contact Page')], max_length=50, unique=True)),
                ('image', models.ImageField(upload_to='headers/')),
                ('title', models.CharField(help_text='The big title shown on the image', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
