# Generated by Django 6.0.4 on 2026-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pageheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leader',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/'),
        ),
    ]
