# Generated by Django 6.0.4 on 2026-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_leader_bio_alter_leader_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ministry',
            name='custom_link',
            field=models.CharField(blank=True, help_text='Optional: Direct this button to a specific page (e.g., /church-kirugu/)', max_length=500, null=True),
        ),
    ]
