# Generated by Django 6.0.5 on 2026-06-04 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ministry_custom_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ministry_highlights/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='core.ministry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
