# Generated by Django 6.0.5 on 2026-06-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ministryhighlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinistryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField(help_text='Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=xyz)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.ministry')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
